# Site settings
title: Sophia Mick's Portfolio
author: Sophia Mick

# URL settings
url: "https://micksoph.github.io"
baseurl: ""

# Navigation links
navbar-links:
  About Me: "aboutme"
  Interests: "interests"
  Travels: "travels"
  Contact: "contact"

# Social network links
social-network-links:
  email: "micksoph@msu.edu"
  github: micksoph
  linkedin: sophiamick
  telephone: +2676350397

# RSS settings
rss-description: This website is a virtual proof that I'm awesome

# Additional settings
date_format: "%B %-d, %Y"
paginate: 5
markdown: kramdown
highlighter: rouge
